# Generated by Django 3.2.16 on 2024-12-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Опыт работы')),
                ('biography', models.TextField(blank=True, verbose_name='О враче')),
                ('photo', models.ImageField(blank=True, upload_to='doctors_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
